name: versioning
description: Versioning
inputs:
  version_name:
    description: Version name
    required: false
runs:
  using: composite
  steps:
  - uses: actions/download-artifact@v3.0.1
    with:
      path: packages/core/dist
  - name: Tag
    run: echo "${{ inputs.version_name }}-$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > packages/core/dist/version
    shell: bash
